### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by huguanjing** [Wendellab/MolEcol2016#1]

**Comment by Jonathanfoxwendel** [comment]
What's this?

Sent from my iPhone

On Feb 22, 2016, at 11:06 AM, Guanjing Hu <notifications@github.com<mailto:notifications@github.com>> wrote:

##

**Comment by huguanjing** [comment]
nothing important. trying to lead scripts to the folder, but forgot how to
use it....

On Mon, Feb 22, 2016 at 10:11 AM, Jonathanfoxwendel <
notifications@github.com> wrote:

> What's this?
> 
> Sent from my iPhone
> 
> On Feb 22, 2016, at 11:06 AM, Guanjing Hu <notifications@github.com
> <mailto:notifications@github.com>> wrote:
> 
> ## 
> 
> Reply to this email directly or view it on GitHub<
> https://github.com/Wendellab/MolEcol2016/issues/1>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Wendellab/MolEcol2016/issues/1#issuecomment-187248253
> .

## 

Guanjing Hu, PhD
Postdoc Research Associate
Department of Ecology, Evolution, and Organismal Biology
Iowa State University, Ames IA, 50011
hugj2006@iastate.edu
huguanjing@gmail.com
